### ISSUE TITLE
The documentation of MCMC kernels used in the E step does not match the implementation

### ISSUE THREAD

**Issue by jranke** [saemixdevelopment/saemixextension#26]
In the [documentation](https://github.com/saemixdevelopment/saemixextension/blob/a490724dc48cc1b02b6842c011327971dd267921/documentation/methodo_saem.tex#L121-L140), four transition kernels for phi are described. The first kernel is the prior distribution of phi_i, the second kernel is a random permutation of the phi_i, kernel three is a multidimensional random walk, and kernel four is a succession of unidimensional random walks.

In the [implementation](https://github.com/saemixdevelopment/saemixextension/blob/a490724dc48cc1b02b6842c011327971dd267921/R/main_estep.R#L26-L96), there are three kernels for eta_i plus the new kernel from Belhals method. The first three kernels are, as far as I can see, the ones described in Marc Lavielles book, pages 256 and 257, i.e. the first is equivalent to the one in the docs, there is no kernel with a random permutation, the second is a series of unidimensional random walks with a calibrated acceptance ratio (this should also be mentioned in the docs), and the third is a (series of?) multidimensional random walks, also with a calibrated acceptance ratio.

**Comment by ecomets** [comment]
Cheers, I'd been meaning to get back to that discrepancy ! I am clarifying this in the documentation now.
