### ISSUE TITLE
compare.saemix does not use the method argument

### ISSUE THREAD

**Issue by jranke** [saemixdevelopment/saemixextension#6]
If one uses "ll" as suggested in the current documentation, the result for importance sampling is returned.

I would propose to change the interface to

```
compare.saemix<-function(..., method = c("is", "lin", "gq") {
```

Then the models would not need to be combined in a list to be compared. I believe it would be OK to make this change to the function interface as the function is not present in the CRAN version of saemix.

I would also propose to stop if the requested likelihood is not available, as calculation the likelihood with the "gq" method can take a very long time (I am currently waiting for the results for my fits) and the user may not be prepared for that.

**Comment by BelhalK** [comment]
Indeed! the method is not presented as a mandatory argument in `compare.saemix`.
Adding this for clarity is a good idea.

Thank you @jranke
